name: "build"

on: [ "pull_request", "push" ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ "ubuntu-latest" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout Repository and Submodules"
        uses: "actions/checkout@v4"
        with:
          submodules: recursive

      - name: "Validate gradle wrapper"
        uses: "gradle/wrapper-validation-action@v3"

      - name: "Setup JDK ${{ matrix.java }}"
        uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"

      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"

      - name: "Build with Gradle"
        run: "./gradlew clean build shadowJar"

      - name: "Upload JAR as Artifact"
        uses: "actions/upload-artifact@v3"
        with:
          name: "core-shadowJar"
          path: "core/build/libs/*.jar"
